### PR TITLE
Support Macosx aarch64

### PR DESCRIPTION
**Pull request by hocesjc**
Resolves https://github.com/eclipsesource/megit/issues/27

### CODE REVIEW

**Review by planger — APPROVED** [review]
Thank you for your contribution! Build works for me and changes look good.

I've added the built archive for MacOS aarch64 to https://github.com/eclipsesource/megit/releases/tag/v0.3.0. Can you please let me know if the built archive works for you?

**Comment by hocesjc** [comment]
It don't work says the same of https://github.com/eclipsesource/megit/issues/10

when i build it local in local it work ok.

**Comment by hocesjc** [comment]
image

**Comment by planger** [comment]
Hm, it looks like we need to run `xattr` after a build on the binaries for Mac. Does it work if you run `sudo xattr -rd com.apple.quarantine ./Eclipse.app`?

I guess we should consider building in a Github action and automate that, as it starts to involve some specific steps.

**Comment by hocesjc** [comment]
It work with sudo xattr -rd com.apple.quarantine ./Eclipse.app 

thanks

**Pull request merged**
